spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: demo
    password: demo
  thymeleaf:
    prefix: classpath:/templates
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
  resources:
    chain:
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /**
  profiles:
    include: common,unittest

security:
  user:
    password: password
  basic:
    enabled: false

server:
  session:
    timeout: 7200
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript

logging:
  file: "/var/log/cloud-webapp.log"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%thread][%-5level][%-40.40logger{39}] :%msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%thread][%-5level][%-40.40logger{39}] :%msg%n"
  level:
    root: INFO
    com.example.jwt_demo.cloud_webapp: DEBUG
    org.hibernate: ERROR
